### ISSUE TITLE
Error when app is builded in release mode

### ISSUE THREAD

**Issue by francescogatto** [haroldadmin/NetworkResponseAdapter#48]
Hi!
I have this error while trying to use an API with my app:

```
E/c: java.lang.RuntimeException: Failed to invoke private l9.i() with no args
        at com.google.gson.internal.m.a(:5)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:3)
        at vf.c.b(:2)
        at vf.c.a(:1)
        at retrofit2.c0.f(:7)
        at retrofit2.y.a(:1)
        at zd.g.run(:7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.InstantiationException: Can't instantiate abstract class l9.i
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.google.gson.internal.m.a(:1)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:3) 
        at vf.c.b(:2) 
        at vf.c.a(:1) 
        at retrofit2.c0.f(:7) 
        at retrofit2.y.a(:1) 
        at zd.g.run(:7) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 

```
With mapping file l9.i() is com.haroldadmin.cnradapter.NetworkResponse -> l9.i

i m using the last stable AS arctic fox, with the latest Gradle plugin. 
I don't have this error with  Gradle 6.7.1 and kotlin 1.5.10

**Comment by haroldadmin** [comment]
Closing this due to lack of a response. Feel free to re-open if you continue to have this issue.
